### ISSUE TITLE
shape of the bullets looks square,should be circle as per design

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#100]
![image](https://user-images.githubusercontent.com/4660706/143541318-d3ed9415-c599-47cb-8cac-881f8790da9f.png)

**Comment by MamataNivajekar** [comment]
@snehaajency couldn't replicate
![image](https://user-images.githubusercontent.com/81617777/144805649-c68ebad1-8d3d-4b22-9d0f-506633ad356d.png)
