### ISSUE TITLE
desktop / the alignment of logo and below labels are not proper

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#102]
1024*768

![image](https://user-images.githubusercontent.com/4660706/143542078-a0a3317d-1ba5-4962-8d06-4c054453121c.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143542113-5e7ff59c-d88a-4155-8b0b-af18c4b9e5bc.png)

**Comment by EktaNaik** [comment]
Fixed.
