### ISSUE TITLE
following things needs to be on one line as per design

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#105]
![image](https://user-images.githubusercontent.com/4660706/143543583-06afccaa-6333-4fc4-ac0d-5ba42b5110b2.png)

![image](https://user-images.githubusercontent.com/4660706/143543762-9ab07874-dda4-48a4-a991-eb37825aa1ee.png)

**Comment by MamataNivajekar** [comment]
@snehaajency It depends on screen width
