### ISSUE TITLE
footer / alignemnt of footer content is not proper

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#106]
![image](https://user-images.githubusercontent.com/4660706/143543878-108f4ee8-c2e8-4484-b967-897e6e743c2f.png)

**Comment by MamataNivajekar** [comment]
@snehaajency I have set the alignment as per design

design:
![image](https://user-images.githubusercontent.com/81617777/144797923-7b0cb05c-83b8-47cc-a85d-30e97ca935e8.png)
