### ISSUE TITLE
desktop/ firefox / alignment of 'latest & trending articles.." wrt below para is not proper

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#109]
browser: firefox
screen : 1280*720
![Home-Healthkart-Blog(1)](https://user-images.githubusercontent.com/4660706/143547029-632ae819-358a-43e3-8154-0ba650ef4ef3.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143547079-19251739-f9b0-434e-8ec3-98d0a91f5489.png)

**Comment by EktaNaik** [comment]
Fixed.
