### ISSUE TITLE
Single blog post: Tags are missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#111]
Description:
Tags are missing after the share buttons (marked in blue in screenshot 2)

Screenshots:
From the staging (screenshot 1)
![image](https://user-images.githubusercontent.com/75774252/145800323-3ed63fef-d4ad-41df-a09a-b60fb361488a.png)

From the design (Screenshot 2)
![image](https://user-images.githubusercontent.com/75774252/145800475-2266c3ef-9d0f-4764-9557-692aa3e6e281.png)

Post link:
https://staging-healthtkart.kinsta.cloud/connect/weight-loss-diet-8-popular-diets-that-can-help-you-lose/

**Comment by MamataNivajekar** [comment]
@ShivaniAjency That post may not have tags, you can check this post --> https://staging-healthtkart.kinsta.cloud/connect/how-your-ideal-workout-plan-should-look-like/bid-8327
