### ISSUE TITLE
Infographics Blog page: The infographics are not visible in the content area

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#113]
Description:
The infographics are not visible in the content area. Only the text content is visible whereas according to the Shared design the graphical content too should be visible

Screenshot:
From the staging
![image](https://user-images.githubusercontent.com/75774252/145807183-24af060b-209b-4cf5-bd7b-5f17b37f1f36.png)

From the design
![image](https://user-images.githubusercontent.com/75774252/145807280-7b75d0a2-3585-4d20-ab07-fb18da81060c.png)

![image](https://user-images.githubusercontent.com/75774252/145807399-e4de2d71-f8de-4eb8-8c84-5b791623d202.png)

**Comment by MamataNivajekar** [comment]
@EktaNaik As we discussed earlier, these infographic images should be added manually using the WordPress post editor.
