### ISSUE TITLE
Infographics Blog page: The Tags are missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#115]
Description:
Tags below the share buttons are missing

Screenshots
From the staging
![image](https://user-images.githubusercontent.com/75774252/145808045-aeb85a88-a4e0-408f-a192-094803e1ad15.png)
 
From the design
![image](https://user-images.githubusercontent.com/75774252/145808224-25279e73-0377-48e8-ad13-b6863284d466.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency the blog post doesn't have tags added to it.
