### ISSUE TITLE
Transformation Blog page: Tags below the share buttons are missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#116]
Description:
Tags below the share buttons are missing

Screenshots
From the staging
![image](https://user-images.githubusercontent.com/75774252/145810880-86dfa77e-786d-44fc-9729-eced960e2bcb.png)

From the design
![image](https://user-images.githubusercontent.com/75774252/145811471-23f8e45b-8f84-43df-83b6-09bb60db96d1.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency That post may not have tags, you can check this post --> https://staging-healthtkart.kinsta.cloud/connect/ashishs-never-give-up-attitude-transformed-him-to-a-fit-freak/tid-699
