### ISSUE TITLE
Video Blog page: Video is not getting displayed full width above the title

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#118]
Description:
The video should get displayed full width above the title 

Screenshot: 
From the staging
![image](https://user-images.githubusercontent.com/75774252/145814867-9c5fad22-f3f6-4cd8-88ab-e61da3977c7e.png)

From the design
![image](https://user-images.githubusercontent.com/75774252/145815351-a879bb22-23e3-4866-8fde-d0e5814df6a7.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Couldn't replicate the issue. it looks like an old design, please check this link in incognito --> https://staging-healthtkart.kinsta.cloud/connect/video/the-story-of-restart-phir-se-zidd-kar-by-muscleblaze-x-vidyut-jammwal/

**Comment by ShivaniAjency** [comment]
@MamataNivajekar Got it After hard refreshing multiple times in incognito. Thank You
