### ISSUE TITLE
Video Blog page: Related articles are getting displayed in the right hand side

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#120]
Description:
Related articles section is getting displayed on the right hand side where as in the design provided there is no section called as Related articles on a video blog page

Screenshots
From the staging
![image](https://user-images.githubusercontent.com/75774252/145817321-bc85a002-71d1-4195-bf69-70e0a05972bd.png)

Design
![image](https://user-images.githubusercontent.com/75774252/145817493-c4143ff1-ab92-41e0-badb-cfbe8965fc1d.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Couldn't replicate the issue. it looks like an old design, please check this link in incognito --> https://staging-healthtkart.kinsta.cloud/connect/video/the-story-of-restart-phir-se-zidd-kar-by-muscleblaze-x-vidyut-jammwal/
