### ISSUE TITLE
Video Blog page: Tags are not getting display

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#122]
Description:
Tags below the share buttons are missing

Screenshot:
from the design
![image](https://user-images.githubusercontent.com/75774252/145819219-61f5b53b-8023-4bab-b60c-40e8efbe455a.png)

 From the staging
![image](https://user-images.githubusercontent.com/75774252/145819318-23e60bf5-da39-4b1a-ad68-c523d656d5f0.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Couldn't replicate the issue. it looks like an old design, please check this link in incognito --> https://staging-healthtkart.kinsta.cloud/connect/video/the-story-of-restart-phir-se-zidd-kar-by-muscleblaze-x-vidyut-jammwal/

**Comment by ShivaniAjency** [comment]
Got it after refreshing multiple times
