### ISSUE TITLE
Video blog post: Read these next should be displayed as tabs

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#123]
Description:
Read these next should be displayed as tabs. Currently they are getting displayed as lists

Screenshots:
Site
![image](https://user-images.githubusercontent.com/75774252/145819881-f921b372-7290-45a6-8613-acfb3d2f923f.png)

Design
![image](https://user-images.githubusercontent.com/75774252/145820184-c297cf64-3141-4972-935d-6afd6246d480.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency  Couldn't replicate the issue. it looks like an old design, please check this link in incognito --> https://staging-healthtkart.kinsta.cloud/connect/video/the-story-of-restart-phir-se-zidd-kar-by-muscleblaze-x-vidyut-jammwal/

**Comment by ShivaniAjency** [comment]
Got it after refreshing multiple times
