### ISSUE TITLE
Video Blog page: Separator is missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#125]
Description:
Separator above the **what to read next** section  is missing

Screenshots:
Site:
![image](https://user-images.githubusercontent.com/75774252/145823163-101ed608-a761-484a-86a0-2927285f0bc2.png)

Design:
![image](https://user-images.githubusercontent.com/75774252/145823233-2673124f-8c38-4517-b729-fe23481158ea.png)

**Comment by MamataNivajekar** [comment]
@ShivaniAjency Couldn't replicate the issue. it looks like an old design, please check this link in incognito --> https://staging-healthtkart.kinsta.cloud/connect/video/the-story-of-restart-phir-se-zidd-kar-by-muscleblaze-x-vidyut-jammwal/
