### ISSUE TITLE
Single blog post - mWeb: Post images appear stretched

### ISSUE THREAD

**Issue by EktaNaik** [ajency/hk_blog#128]
**Issue**: 

- Post images appear stretched on mobile.

**Screenshot**:
![image](https://user-images.githubusercontent.com/44566188/145826196-497a5f53-c4af-45d5-9921-6ef68cec344d.png)

**Comment by MamataNivajekar** [comment]
@EktaNaik  couldn't replicate the issue.
![image](https://user-images.githubusercontent.com/81617777/145937265-93606020-6f88-4175-80aa-16c852ef406a.png)

**Comment by EktaNaik** [comment]
@MamataNivajekar check this post on mobile:
https://staging-healthtkart.kinsta.cloud/connect/cms/top-7-best-whey-protein-powders-of-2020/bid-10191

**Comment by EktaNaik** [comment]
Fixed.
