### ISSUE TITLE
Single blog page: Tags are not working correctly

### ISSUE THREAD

**Issue by EktaNaik** [ajency/hk_blog#141]
**Issue**:

- Tags added on blog posts should redirect to the Tag landing page with its list view of all posts containing that Tag.
- Currently all tags on a post redirect to the same post page only.
- See the issue with tags on this post for example - https://staging-healthtkart.kinsta.cloud/connect/5-ways-to-build-lean-muscle-gain/

**Expected Behavior:**
Tag Page on live - https://www.healthkart.com/connect/tag/abs-workout/

**Comment by MamataNivajekar** [comment]
@EktaNaik https://www.healthkart.com/connect/tag/abs-workout/ --> this tag has only 1 post
you can check this tag page for reference --> https://www.healthkart.com/connect/tag/antioxidant/
