### ISSUE TITLE
Homepage > Subscribe to HK blog section, change placeholder text to " Enter your Email "

### ISSUE THREAD

**Issue by HazelColaco19** [ajency/hk_blog#17]
Website:

![image](https://user-images.githubusercontent.com/55691499/95865015-ca3ffc80-0d83-11eb-9fe5-e7b27eaba948.png)

design:

![image](https://user-images.githubusercontent.com/55691499/95865077-dcba3600-0d83-11eb-8adb-4505c1060a0c.png)

**Comment by saeeshtends** [comment]
Requested by client on call

**Comment by HazelColaco19** [comment]
Can be closed
