### ISSUE TITLE
Restricting the articles sliding in banner to 5 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#28]
Description:
At present, the number of articles in the sliding banner keeps on increasing with the addition of every new article, The  number of articles in the sliding banner should be restricted to 5

To Reproduce:

- Go to https://www.healthkart.com/connect
- See the banner slider

Expected Behavior:
There should be 5 articles in the sliding banner

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/113132539-359b5f00-923c-11eb-83c1-a0d5d8d00c0a.png)

**Comment by Vaibhavarolkar** [comment]
Use this setting "Banner Article" in backed to show the posts in slider.
Previously posts from sticky post's along with above setting were shown.
Now I have excluded sticky posts and shown posts which has above setting.
@ShivaniAjency @EktaNaik

**Comment by ShivaniAjency** [comment]
Issue fixed
