### ISSUE TITLE
In-app, when we press the back button on the category page or article page, it takes you to the home page of the main domain 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#31]
Description:
In-app, when we press the back button on the category page or article page, it takes you to the home page of the main domain 

Expected Behaviour:
It should take you to the home page of connect blog.

Refer [this](https://drive.google.com/file/d/1hDtBuXKYnHB-DZBvt8koXleuCyD-BXo4/view )

**Comment by EktaNaik** [comment]
Issue to be handled by HK's tech team.
