### ISSUE TITLE
Blog menu does not appear in app view

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#32]
Description:
In-app, The  Blog menu does not appear.

Expected Behaviour:
Blog menu should appear in the app

Refer [this]( https://drive.google.com/file/d/1hL-NdmVOaJph8VyhzmnZ2SCeFykcvBj1/view?usp=drivesdk )

**Comment by EktaNaik** [comment]
Issue to be handled by HK's tech team.
