### ISSUE TITLE
Thumbnail image of the transformation blogs are getting cropped

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#38]
Description:
The Thumbnail image of transformation blogs is not showing properly. Images are getting cropped. This can be  due to the dimensions of the image
(Description as in the sheet: Thumbnail image of transformation blogs are not showing properly. Provide option to upload thumbnail image separately )

Expected outcome:
The thumbnail images should not get cropped.

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/113251519-076f5b00-92e0-11eb-9678-56a310c67cd9.png)

**Comment by chaitanya-ajency** [comment]
https://staging-healthtkart.kinsta.cloud/connect/transformation/?page=1

**Comment by chaitanya-ajency** [comment]
option Provided to upload thumbnail image separately - [Screenshot](https://i.ibb.co/sm6Pkdq/screenshot-staging-healthtkart-kinsta-cloud-2021-05-25-19-55-57.png)

**Comment by snehaajency** [comment]
fixed 
![image](https://user-images.githubusercontent.com/4660706/119608474-a6619080-be13-11eb-967b-b52e4ab7a112.png)

**Comment by snehaajency** [comment]
fixed
