### ISSUE TITLE
Spacing between numbers/ bullets in content and in category pages

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#39]
Description:
There is no proper spacing between numbers/ bullets in content and in category pages

View  the issue [here](https://www.healthkart.com/connect/cms/how-to-use-whey-protein-powder-to-lose-weight/bid-10179)

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/113254792-a72ee800-92e4-11eb-8139-837bef302159.png)

**Comment by chaitanya-ajency** [comment]
[https://staging-healthtkart.kinsta.cloud/connect/cms/how-to-use-whey-protein-powder-to-lose-weight/bid-10179](url)

**Comment by chaitanya-ajency** [comment]
![Uploading screenshot-staging-healthtkart.kinsta.cloud-2021.05.25-19_24_07.png…]()

**Comment by chaitanya-ajency** [comment]
https://www.healthkart.com/connect/cms/how-to-use-whey-protein-powder-to-lose-weight/bid-10179

**Comment by chaitanya-ajency** [comment]
Issue fixed.. PLease find the page [here](https://www.healthkart.com/connect/cms/how-to-use-whey-protein-powder-to-lose-weight/bid-10179)

**Comment by chaitanya-ajency** [comment]
Issue fixed.. Please find the link [here](https://staging-healthtkart.kinsta.cloud/connect/cms/how-to-use-whey-protein-powder-to-lose-weight/bid-10179)

**Comment by snehaajency** [comment]
fixed 
![image](https://user-images.githubusercontent.com/4660706/119607425-ee7fb380-be11-11eb-929d-000db01f1266.png)
