### ISSUE TITLE
Increase the bullet size in mobile/app view

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#40]
Description:
The bullet size in the app view appears small

Expected behaviour:
Increased bullet size in mobile/app view

Screenshot:
https://drive.google.com/file/d/1i0bCEmMIYd9jASsHNoN8coGjgpKEvVtx/view

**Comment by chaitanya-ajency** [comment]
Issue fixed.. Please find the link here

**Comment by snehaajency** [comment]
![image](https://user-images.githubusercontent.com/4660706/119607214-87fa9580-be11-11eb-966c-8fe865e540e6.png)
fixed
