### ISSUE TITLE
Product widget implementation

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#42]
**Description:**
The product widget should be displayed.

**Brief:**
A section displaying 5-6 of their products should be present preferably products belonging to that particular category. For example: for the muscle gain category we can have a section that displays the muscle gain products.

**History:**
_Refer:_
http://web.archive.org/web/20201128134934/https://www.healthkart.com/connect/10-best-weight-gain-smoothies/bid-4477
we can see that under muscle gain they have displayed the products which assist in gaining muscles. A similar concept can be applied to the current site where the data can be added statically along with a button redirecting towards the main product page on their original site can be added. (Blue highlight)

**Reference screenshot:**
![image](https://user-images.githubusercontent.com/75774252/107030345-82cbf900-67d6-11eb-9c9f-3f645b5dcb30.png)

**Remarks:
For the product widget, we will need the product listing APIs that were being used on the older site so that we can use them to fetch products from the main HK site; OR we can create a static widget to display the select products

**HK Team to confirm****

**Comment by EktaNaik** [comment]
**Issue:**
Some posts do not show any recommended product - https://staging-healthtkart.kinsta.cloud/connect/6-healthy-valentine-treats/

**Need clarification on:**

1. What is the max limit set? Some posts show 2 products while some show 4 - https://staging-healthtkart.kinsta.cloud/connect/6-healthy-valentine-treats/
> Limit to be set as 6

3. If limit is already set, for example if 4 is the current max limit, if a category has 10 products which 4 products will be displayed? Products sorted by date of creation, or alphabetical order?

**Comment by ankitasangodkar** [comment]
1. Product cards show too much blank space in mobile view. (If this was done in order to adjust long product names, place truncate the title if it goes beyond 2 lines). - **Fixed**

2. As per the older UI reference shared, product cards should be 2 in a row; currently it is 1 in a row. - **Fixed**
