### ISSUE TITLE
Decrease the font-size of H3 tag or fix the alignment issue for this page

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#50]
Description:
Decreasing the size of the h3 tag and keeping it less than h2 or fixing the alignment for these pages. The current font size of the h3 tag is 15px and h2 is 2rem

Screenshots:
![image](https://user-images.githubusercontent.com/75774252/114884981-d9336480-9e23-11eb-9893-d00c4db54a26.png)

![image](https://user-images.githubusercontent.com/75774252/114885330-2a435880-9e24-11eb-97a8-762143289733.png)

**Comment by EktaNaik** [comment]
Fixed.
