### ISSUE TITLE
Latest article section is not showing the latest articles

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#60]
Description:
The latest article section is not showing the latest articles

Screenshot:
![image](https://user-images.githubusercontent.com/75774252/116099734-e37a1c00-a6c9-11eb-8be6-436310d8986e.png)
The latest article (marked in blue) is not getting displayed at the top. Also article from 2018 is  getting displayed

**Comment by ShivaniAjency** [comment]
Fixed on staging

**Comment by ShivaniAjency** [comment]
On live:
![image](https://user-images.githubusercontent.com/75774252/116548466-e36c5d00-a911-11eb-9eb7-875a587c3ce4.png)

**Comment by ShivaniAjency** [comment]
Fixed on staging as well as live

**Comment by ShivaniAjency** [comment]
Description: The latest articles are not getting displayed on the homepage. If you check the backend then you will see that the latest article posted was on 09/05/2021 and on the front end it is showing 29/04/2021

Screenshot:
Backend:
![image](https://user-images.githubusercontent.com/75774252/117642097-9192c500-b1a4-11eb-9b38-e04f7df41266.png)


Website:
![image](https://user-images.githubusercontent.com/75774252/117642197-a5d6c200-b1a4-11eb-869b-95afe115c6ee.png)

**Comment by ankitasangodkar** [comment]
Posts were made sticky.
Since the older posts were marked as sticky they were shown first and not the recent post.
