### ISSUE TITLE
Before and after image upload section for transformation section  is not visible to the client

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#61]
Description:
The before and after image upload section for the transformation is **not visible to the client** but **the section is visible to the developer and the tester.** Unable to recreate the issue. find the screenshot send by the client below.

https://lh3.googleusercontent.com/-NXZ9eyLXAj4/YIecXqIhMfI/AAAAAAAAAaY/P-hQh8F_WU8hWrxBLp1QSQqZif3V1oPJACK8BGAsYHg/s0/2021-04-26.png?authuser=0

**Comment by ankitasangodkar** [comment]
Using the following credentials the client was not able to see the **before and after** upload section
Username: healthkart
Password:  HKadmin#1234%

For some reason, the image section where we uploaded before and after images have been moved under settings, and its visible there. We can update/change the 
![before-after](https://user-images.githubusercontent.com/42134631/117759907-34e5e780-b242-11eb-8b2f-2241a12f4f5e.png)
image there.
