### ISSUE TITLE
AMP Issue - There are few HTML attributes added in AMP pages which are not allowed. 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#68]
Description:
AMP Issue - There are few HTML attributes added in AMP pages that are not allowed. 

Error 1:
Alt tag appearing in <a> tags: https://www.healthkart.com/connect/nishants-journey-from-skinny-to-muscular/tid-428/amp
![image](https://user-images.githubusercontent.com/75774252/117647873-2c8e9d80-b1ab-11eb-8678-2922082b982f.png)

Error 2:
The tag 'img' may only appear as a descendant of tag 'noscript'. 
Recommendations: Use <amp-img> tag instead of <img> tag.

![image](https://user-images.githubusercontent.com/75774252/117648315-b3437a80-b1ab-11eb-9a6c-7638af5a47f9.png)

Find the doc[ here
](https://drive.google.com/file/d/15c-JT5RSpwlsJpVqNnvlktKlhLS7WYSS/view?usp=sharing)

**Comment by ankitasangodkar** [comment]
Error 1:
Alt tag appearing in anchor tag is fixed

**Comment by ShivaniAjency** [comment]
Issue Fixed
