### ISSUE TITLE
Breadcrumb Issue - Breadcrumb schema is not correct. 

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#69]
Description:
Breadcrumb schema is not correct. It doesn't have the required entities mentioned. check  here  view-source:https://www.healthkart.com/connect/the-inspiring-story-of-wheelchair-bodybuilder-nick-scott/

An example of breadcrumb schema is as follows:
![image](https://user-images.githubusercontent.com/75774252/117649675-6c568480-b1ad-11eb-905f-206f14eac708.png)

**Comment by snehaajency** [comment]
fixed
