### ISSUE TITLE
The downward arrow is missing for the transformation in the menu

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#71]
**Description:**

- The downward arrow for the Transformations in the menu is missing.
- The downward arrow for the Transformations in the menu is specified in the[ design](https://xd.adobe.com/view/461a0d88-76d1-4141-ae7b-5bdb3c632314-1349/specs/)

**Screenshot:**
Given below is the screenshot from the website
![image](https://user-images.githubusercontent.com/75774252/142976374-8ab6dc8a-2cc5-4c9f-8624-d01b041eca62.png)

Given below is the [screenshot of the design provided](https://xd.adobe.com/view/461a0d88-76d1-4141-ae7b-5bdb3c632314-1349/specs/)
![image](https://user-images.githubusercontent.com/75774252/142976488-cbefc866-2b60-41db-a0c0-4d5759b9ac6a.png)

**Comment by EktaNaik** [comment]
@ShivaniAjency There is no submenu under Transformations. Hence no dropdown!
