### ISSUE TITLE
Transformation Stories: 3 slides are getting displayed

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#72]
**Description**

- On the site, 3 slides are getting displayed whereas as per [the design](https://xd.adobe.com/view/461a0d88-76d1-4141-ae7b-5bdb3c632314-1349/specs/) 5 slides should get displayed

**Screenshot:**

-  Given below is the screenshot from the site
![image](https://user-images.githubusercontent.com/75774252/142977625-8a5ddf4c-9ac3-4086-a5bb-69638ef6a940.png)

- Given below is the screenshot from[ the design](https://xd.adobe.com/view/461a0d88-76d1-4141-ae7b-5bdb3c632314-1349/specs/)
![image](https://user-images.githubusercontent.com/75774252/142977713-59c85d74-4a3c-408f-990a-5b97a17f31ba.png)

**Comment by EktaNaik** [comment]
@ShivaniAjency Can be ignore since we are anyway displaying 5 posts in this section.
