### ISSUE TITLE
Explore Articles: Less than 6 articles are getting displayed under all the tabs except Bodybuilding

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#73]
**Description**

- The 2nd, 3rd, 4th, 5th tabs are displaying less than 6 articles

**Required Behavior**

- All the tabs should be like the first one that is Bodybuilding displaying 6 articles

**Screenshots**:
Given below is the screenshot of the  **Hair, skin, and nails** tab
![image](https://user-images.githubusercontent.com/75774252/142978770-c0b0974d-e7c4-48bc-a059-3278cbfecda3.png)

Given below is the screenshot of the Bodybuilding tab:
![image](https://user-images.githubusercontent.com/75774252/142979326-c4736d12-1bca-44c5-852b-88cd45313a4a.png)

**Comment by EktaNaik** [comment]
Fixed.
