### ISSUE TITLE
Trending Infographics: Differences in the height of displayed infographics

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#74]
**Description:**

- The height of the displayed infographics in the second row are unequal.

**Required Behavior:**

- All the infographics displayed under the Trending Infographics section should be of equal height (like how they are in the first row)

**Screenshot:**
![image](https://user-images.githubusercontent.com/75774252/142981504-47c3bafd-86d2-4ecc-8456-e562d8f914fb.png)

**Comment by EktaNaik** [comment]
Fixed.
