### ISSUE TITLE
Footer: Connect With Us section is missing below the subscribe form

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#75]
**Description**

- Social media Icons or the Connect With Us section is missing below the subscribe form

**Required behavior:**
Connect with us section should be placed below the subscribe form as given in the design

**Screenshots:**
Given below is the screenshot of the site
![image](https://user-images.githubusercontent.com/75774252/142983899-fae6472c-c87e-4561-a4f1-a60586cea16e.png)

Given below is the screenshot from the design 
![image](https://user-images.githubusercontent.com/75774252/142983977-85bafb87-56b0-42c0-b749-d94774978e2e.png)

**Comment by EktaNaik** [comment]
Fixed.
