### ISSUE TITLE
Footer: should have 6 columns, at present there are 5

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#76]
**Description**
The footer consist of 5 columns

**Requirement:**
The design shows 6 columns in the footer

**Screenshot:**
Given below is the screenshot from the design
![image](https://user-images.githubusercontent.com/75774252/142984342-7b2f0411-be8d-408f-8877-28d28e99891e.png)

Given below is the screenshot from the site
![image](https://user-images.githubusercontent.com/75774252/142984448-5202de74-8b03-4b5f-9ec4-84083721ccfd.png)

**Comment by EktaNaik** [comment]
Fixed.
