### ISSUE TITLE
Footer: "About healthkart" is missing above the subscribe form

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#77]
**Description**
'About healthkart' section is missing above the 'Subscribe to our newsletter' form

**Requirement:**
"About healthkart" should be placed above the "Subscribe to our newsletter"

**Screenshot:**

Given below is the screenshot from the design
![image](https://user-images.githubusercontent.com/75774252/142985163-7e22720f-ded3-4797-b9f3-a78ed4aad30a.png)

Given below is the design from the site:
![image](https://user-images.githubusercontent.com/75774252/142985212-6ad14e1e-cd97-4a3e-9a57-9453dfee69c3.png)

**Comment by EktaNaik** [comment]
Fixed.
