### ISSUE TITLE
Footer: Disclaimer and icons are missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#78]
**Description**
The disclaimer is not getting displayed immediately after the footer columns and the icons are missing. At present the disclaimer is getting displayed at the end of the page

**Required Behavior:**
The disclaimer and the icons should get displayed immediately after the footer columns as shown in the design

**Screenshot:**
Given below is the screenshot from the design
![image](https://user-images.githubusercontent.com/75774252/142986017-4f2f16ee-2011-4661-b4ec-350b66c7f74f.png)

Given below is the screenshot from the site
![image](https://user-images.githubusercontent.com/75774252/142986168-ec662d5c-ab18-4904-9e1b-d396b325bb4d.png)

**Comment by EktaNaik** [comment]
Fixed.
