### ISSUE TITLE
Footer: Payment modes are displayed

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#79]
**Description**
The payment modes are displayed in the footer

**Requirement:**
The payment modes should not be displayed in the footer as per the design

**Screenshot:**

Given below is the screenshot from the site
![image](https://user-images.githubusercontent.com/75774252/142986979-41fb67f8-ce26-4792-8ddf-1fdf28328468.png)

**Comment by EktaNaik** [comment]
Fixed.
