### ISSUE TITLE
Footer: Download Our app section missing

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#80]
**Description**
Download our app section is missing in the footer

**Behavior:**
The footer should contain Download our apps section as in the design

**Screenshot:**
Given below is the screenshot from the design
![image](https://user-images.githubusercontent.com/75774252/142987911-5277ba93-e27e-46ba-b962-8ce6224a19f0.png)

Given below is the screenshot from the site:
![image](https://user-images.githubusercontent.com/75774252/142987977-be887b15-8c5c-4674-8c3d-a37394d07654.png)

**Comment by EktaNaik** [comment]
@MamataNivajekar The app icons need to be hyper linked same as that on the live Healthkart website footer.

Reference - https://www.healthkart.com/

Issue screenshot - 
![image](https://user-images.githubusercontent.com/44566188/145568717-5495c6d8-ce7e-4db8-8a1f-f21527afb02f.png)

**Comment by EktaNaik** [comment]
Fixed.
