### ISSUE TITLE
Background color of the copyright should be the same as footer color

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#81]
Description:

- Copyright has a white background

Requirement
The background color of the copyright should be as same as the footer

Screenshot:
Given below is the screenshot from live
![image](https://user-images.githubusercontent.com/75774252/142992583-fa4455c5-1d54-4a3d-840b-c0ef6dcf2438.png)

**Comment by EktaNaik** [comment]
Fixed.
