### ISSUE TITLE
Floating Social media widget to be removed

### ISSUE THREAD

**Issue by ShivaniAjency** [ajency/hk_blog#82]
**Description:**

- The site has a floating widget of social media icons

**Requirement:**

The side should not have a floating social media widget . The design shared does not have the floating widget

**Screenshot:**
![image](https://user-images.githubusercontent.com/75774252/142996979-c173a011-75df-4389-a808-4a1db56d5a0e.png)

**Comment by EktaNaik** [comment]
@ShivaniAjency Design does not have it yes, but it is required. So please ignore.
