### ISSUE TITLE
Mobile / the color of hamburger menu is not matching design

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#84]
![image](https://user-images.githubusercontent.com/4660706/143535176-7a7cc247-bca9-49d4-a1f6-cce19033d99a.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143535225-1704d767-0b70-4133-a345-ba75e8bc5db9.png)

**Comment by EktaNaik** [comment]
Fixed.
