### ISSUE TITLE
mobile / text is touching the top of card as per design some space is needed

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#85]
![image](https://user-images.githubusercontent.com/4660706/143535531-2770c39a-baa6-4b40-bd5e-9618879f1aec.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143535663-2102cce8-4f9a-4f77-b798-0e2bff93d53c.png)

**Comment by EktaNaik** [comment]
Fixed.
