### ISSUE TITLE
mobile / More articles / the container size increases as we swipe

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#87]
https://drive.google.com/file/d/1jh94d4fHb_-G5_2-HUj-7pGgg_G2-s17/view?usp=sharing

**Comment by MamataNivajekar** [comment]
@snehaajency container size depends on the content inside.

**Comment by EktaNaik** [comment]
@MamataNivajekar the height of each slide in the More Articles slider needs to be consistent.
For instance, maintain the same line height for Titles (2 lines) and Excerpt (3 lines) of each post in the slider.

Screenshot:
![image](https://user-images.githubusercontent.com/44566188/145570277-d5b8420a-1ca6-4321-9749-dc0b118dc0f8.png)

**Comment by EktaNaik** [comment]
Fixed.
