### ISSUE TITLE
Mobile / the weight of the icons '+'/'-' looks more as compared to dsign

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#89]
![image](https://user-images.githubusercontent.com/4660706/143537211-dd1c8b70-071c-4760-8c7b-4d71325f1aca.png)

design:
![image](https://user-images.githubusercontent.com/4660706/143537241-bbfc4abe-eef3-4e30-850b-474e784e9d07.png)

**Comment by EktaNaik** [comment]
Fixed.
