### ISSUE TITLE
laptop / the alignment of 'more articles' with below paragrapgh is notproper

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#97]
![image](https://user-images.githubusercontent.com/4660706/143540264-f81065b2-c886-434f-9c25-401c3596348d.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143540303-41e0ec6b-3028-46c8-95e3-33fa178cebe2.png)

**Comment by EktaNaik** [comment]
Fixed.
