### ISSUE TITLE
fontweight looks more for  header labels

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#98]
![image](https://user-images.githubusercontent.com/4660706/143540642-6f3364f4-7897-4dbd-877d-26025a6709b5.png)

expected:
![image](https://user-images.githubusercontent.com/4660706/143540703-e1f9f03c-f1ce-4762-8424-0c27f6a6ebc1.png)

**Comment by EktaNaik** [comment]
Fixed.
