### ISSUE TITLE
the alignment of footer and the body doesnt look proper

### ISSUE THREAD

**Issue by snehaajency** [ajency/hk_blog#99]
![image](https://user-images.githubusercontent.com/4660706/143541171-a9dca356-71e4-4b4a-b88f-8d54f5012bb7.png)

design:
![image](https://user-images.githubusercontent.com/4660706/143541218-1a1fb228-88a0-4d6f-9914-9d66c3e77759.png)

**Comment by MamataNivajekar** [comment]
@snehaajency Since in the design footer is a screenshot taken from the [healthkart](https://www.healthkart.com/) site (from a larger screen), it's not possible to calculate the inner width of the footer.  So I have added a similar container width for the footer that we have used for other sections.
